---
- hosts: all
  user: all
  tasks:
#    - name: Update and upgrade apt packages
#      become: true
#      apt:
#        upgrade: "yes" # not: yes
#        update_cache: yes
#        cache_valid_time: 86400 #One day
#    - name: ensure openjdk-8-jdk is at the latest version
#      become: true
#      apt: name=openjdk-8-jdk state=latest
#    - name: download spark in local
#      connection: local
#      shell: 'wget http://mirror.navercorp.com/apache/spark/spark-3.0.2/spark-3.0.2-bin-hadoop2.7.tgz'
#      ignore_errors: yes # 복잡한 글이 나오는데 이걸 error로 안 여긴다!
#    - name: store file to remote server
#      copy:
#        src: spark-3.0.2-bin-hadoop2.7.tgz
#        dest: ~/spark-3.0.2-bin-hadoop2.7.tgz
#    - name: download store file
#      get_url:
#        url: http://mirror.navercorp.com/apache/spark/spark-3.0.2/spark-3.0.2-bin-hadoop2.7.tgz
#        dest: ~/spark-3.0.2-bin-hadoop2.7.tgz
    - name: spark configuration
      become: true
      shell: tar -xvf spark-3.0.2-bin-hadoop2.7.tgz -C /opt/
# 현재 다운받은 스파크 파일이 안 지워지고 있음
    - name: del spark file
      become: true
      file:
        path: ~/spark-3.0.2-bin-hadoop2.7.tgz
        state: absent
    - name: Creates directory
      become: true
      file:
        path: /opt/spark
        state: directory
# 원래를 그냥 명령어로 아래와 같이 했지만, 앤서블 코드로 바꾸고 있음
#    - name: move spark file
#      become: true
#      command: mv /opt/spark-3.0.2-bin-hadoop2.7/ /opt/spark/
# 폴더를 복사하고 지운다.
    - name: Copy files from foo to bar
      become: true
      copy:
        remote_src: true
        src: /opt/spark-3.0.2-bin-hadoop2.7/
        dest: /opt/spark/
    - name: del /opt/spark-3.0.2-bin-hadoop2.7
      become: true
      file:
        path: /opt/spark-3.0.2-bin-hadoop2.7
        state: absent
# 현재 chown를 앤서블 코드로 못 바꾸고 있음
# 아래와 같이 경고가
# [WARNING]: Consider using the file module with owner rather than running 'chown'.  If you need to use command because file is insufficient you can add 'warn: false' to this command task or set 'command_warnings=False' in ansible.cfg to get rid of this message.
    - name:  chown spark
      become: true
      command: chown pi:pi -R /opt/spark
# 설치가 끝났으면 리부팅합니다.
    - name: Reboot the server and wait for it to come back up.
      reboot: