---
- hosts: all
  user: all
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: "yes" # not: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
    - name: ensure openjdk-8-jdk is at the latest version
      become: true
      apt: name=openjdk-8-jdk state=latest
    - name: download hadoop
      get_url:
        url: https://downloads.apache.org/hadoop/common/hadoop-3.2.1/hadoop-3.2.1.tar.gz
        dest: ~/hadoop-3.2.1.tar.gz
    - name: Creates directory
      become: true
      file:
        path: /opt/hadoop
        state: directory      
    - name: unzip Hadoop.tgz
      become: true
      shell: tar -xvf hadoop-3.2.1.tar.gz -C /opt/hadoop
    - name:  chown hadoop
      become: true
      command: chown pi:pi -R /opt/hadoop
# 설치가 끝났으면 리부팅합니다.
      notify:
      - Reboot the server
# handlers 를 이용해 구형하는 경우 윗 chown hadoop를 실행되지 않으면
# handlers 에 들어있는 리부팅이 실행되지 않습니다.
  handlers:
    - name: Reboot the server
      command: sudo reboot
